### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by Chenxi96**
version

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests. (If tests are not applicable, explain why in the next section.)
- [x] Is there only 1 commit.

## Describe your changes
I updated the dependencies version to the latest version.
## Issue ticket number and link
N/A

### CODE REVIEW

**Review by alvinc21 — COMMENTED** [review]
I think we should add the caret (^) symbol for all of the package versions. Give [this document](https://docs.npmjs.com/cli/v6/using-npm/semver) a read and let me know what you think.

**Comment by Chenxi96** [comment]
> I think we should add the caret (^) symbol for all of the package versions. Give [this document](https://docs.npmjs.com/cli/v6/using-npm/semver) a read and let me know what you think.

I've read the document; our goal is to have the version patch and minor to increment up and ensure it is compatible with the older version that we're attempting to update. This will prevent issues with breaking changes that we need to manually fix by rewriting the code.

**Comment by alvinc21** [comment]
> > I think we should add the caret (^) symbol for all of the package versions. Give [this document](https://docs.npmjs.com/cli/v6/using-npm/semver) a read and let me know what you think.
> 
> I've read the document; our goal is to have the version patch and minor to increment up and ensure it is compatible with the older version that we're attempting to update. This will prevent issues with breaking changes that we need to manually fix by rewriting the code.

Yeah I agree. Go ahead and make the changes and this PR should be good to go.

**Review by Chenxi96 — COMMENTED** [review]
The changes has been made, updated the package json file for each dependency version there's a caret to prevent breaking changes and comptability.

**Review by alvinc21 — APPROVED** [review]

**Pull request merged**
